name: Main Branch and Pull Requests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup UV and Python
        uses: ./.github/actions/setup
      - name: Lint
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v6
      - name: Setup UV and Python
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        uses: ./.github/actions/test